#ifndef CADOR_HEADERS
#define CADOR_HEADERS

const char* const VILUNDO_CLIENT_INITIATE = "VL";
const int VILUNDO_CLIENT_INITIATE_ = 2; // length

const char* const VILUNDO_SERVER_INITIATE = "VL";
const int VILUNDO_SERVER_INITIATE_ = 2;

const char* const VILUNDO_AUTH_FAILURE = "\xff";
const int VILUNDO_AUTH_FAILURE_ = 1;

const int VILUNDO_IDENTIFY_MAX_ = 255; // maxlength

unsigned char const VILUNDO_VERSION_MAJOR = 1;
unsigned char const VILUNDO_VERSION_MINOR = 1;

const char VILUNDO_VERSION[] = { VILUNDO_VERSION_MAJOR, VILUNDO_VERSION_MINOR };

enum Vilundo_Privileges {
    VILUNDO_PRIVILEGES_BANNED        = 0,
    VILUNDO_PRIVILEGES_USER          = 10,
    VILUNDO_PRIVILEGES_MODERATOR     = 30,
    VILUNDO_PRIVILEGES_ADMINISTRATOR = 50,
    VILUNDO_PRIVILEGES_DEVELOPER     = 60,
    VILUNDO_PRIVILEGES_NOT_FOUND     = 255
};

enum Vilundo_AuthError {
    VILUNDO_AUTHERROR_LOGIN_INCORRECT    = 0,
    VILUNDO_AUTHERROR_BANNED             = 1,
    VILUNDO_AUTHERROR_OVERLOADED         = 2,
    VILUNDO_AUTHERROR_SERVER             = 3
};

enum Vilundo_JoinRoomError {
    VILUNDO_JOINROOMERROR_NO_SUCH_ROOM   = 0,
    VILUNDO_JOINROOMERROR_NO_PRIVILEGES  = 1,
    VILUNDO_JOINROOMERROR_BANNED         = 2,
    VILUNDO_JOINROOMERROR_OVERLOADED     = 3,
    VILUNDO_JOINROOMERROR_ALREADY_JOINED = 5,
    VILUNDO_JOINROOMERROR_UNKNOWN        = 4
};

enum Vilundo_PartRoomError {
    VILUNDO_PARTROOMERROR_NO_SUCH_ROOM   = 0,
    VILUNDO_PARTROOMERROR_NO_PRIVILEGES  = 1,
    VILUNDO_PARTROOMERROR_ALREADY_PARTED = 3,
    VILUNDO_PARTROOMERROR_LASTROOM       = 4,
    VILUNDO_PARTROOMERROR_UNKNOWN        = 2
};

enum Vilundo_DisconnectError {
    VILUNDO_DISCONNECTERROR_USERQUITS    = 0,
    VILUNDO_DISCONNECTERROR_CLIENTERROR  = 1,
    VILUNDO_DISCONNECTERROR_KILLED       = 128,
    VILUNDO_DISCONNECTERROR_BANNED       = 129,
    VILUNDO_DISCONNECTERROR_OVERLOADED   = 130,
    VILUNDO_DISCONNECTERROR_UPGRADING    = 131,
    VILUNDO_DISCONNECTERROR_SERVER       = 132
};

enum Vilundo_UserListError {
    VILUNDO_USERLISTERROR_NO_PRIVILEGES  = 1
};

enum Vilundo_IncomingPacketHeader {
    VILUNDO_INCOMING_REQUEST_MOTD        = 0x0001,
    VILUNDO_INCOMING_REQUEST_JOIN        = 0x0003,
    VILUNDO_INCOMING_REQUEST_PART        = 0x0006,
    VILUNDO_INCOMING_REQUEST_QUIT        = 0x0009,
    VILUNDO_INCOMING_REQUEST_ACK         = 0x000a,
    VILUNDO_INCOMING_REQUEST_USERINFO    = 0x000c,
    VILUNDO_INCOMING_REQUEST_ROOMINFO    = 0x000e,
    VILUNDO_INCOMING_REQUEST_USERLIST    = 0x1000,
    VILUNDO_INCOMING_ROOM_MESSAGE        = 0x0018,
    VILUNDO_INCOMING_ROOM_MESSAGE_OK     = 0x001c,
    VILUNDO_INCOMING_PRIVATE_MESSAGE     = 0x0012,
    VILUNDO_INCOMING_PRIVATE_MESSAGE_OK  = 0x0016,
    VILUNDO_INCOMING_OVERDOSE            = 0x0010
};

enum Vilundo_OutgoingPacketHeader {
    VILUNDO_OUTGOING_MOTD                = 0x0002,
    VILUNDO_OUTGOING_JOINED              = 0x0004,
    VILUNDO_OUTGOING_JOIN_FAILURE        = 0x0005,
    VILUNDO_OUTGOING_PARTED              = 0x0007,
    VILUNDO_OUTGOING_PART_FAILURE        = 0x0008,
    VILUNDO_OUTGOING_REQUEST_QUIT        = 0x0009,
    VILUNDO_OUTGOING_ACK                 = 0x000b,
    VILUNDO_OUTGOING_USERINFO            = 0x000d,
    VILUNDO_OUTGOING_ROOMINFO            = 0x000f,
    VILUNDO_OUTGOING_USERLIST            = 0x1001,
    VILUNDO_OUTGOING_ROOM_MESSAGE_OK     = 0x0019,
    VILUNDO_OUTGOING_ROOM_MESSAGE        = 0x001b,
    VILUNDO_OUTGOING_PRIVATE_MESSAGE_OK  = 0x0013,
    VILUNDO_OUTGOING_PRIVATE_MESSAGE     = 0x0015,
    VILUNDO_OUTGOING_OVERDOSE            = 0x0011
};

enum Vilundo_Overdose {
    VILUNDO_OVERDOSE_ROOM_START          = 0,
    VILUNDO_OVERDOSE_ROOM_END            = 1,
    VILUNDO_OVERDOSE_PRIVATE_START       = 8,
    VILUNDO_OVERDOSE_PRIVATE_END         = 9
};

#endif

